### ISSUE TITLE
'Namespace' object has no attribute 'data_dir'

### ISSUE THREAD

**Issue by Conor52121** [QizeYang/PAUL#25]
When I use the code supervied_train.py, trouble happened, how should I change it? Thank you.

Namespace(batch_size=48, data='MSMT17Extra', debug=False, epochs=60, evaluate=False, exp_name='0000', gp
u='2', height=384, lr=0.1, margin=1, momentum=0.9, net='PatchNet', print_freq=500, resume='', seed=None,
 start_epoch=0, tloss=0.1, weight_decay=0.0001, width=128, workers=8)
Traceback (most recent call last):
  File "supervised_train.py", line 234, in <module>
    main()
  File "supervised_train.py", line 96, in main
    data = dataset.__dict__[args.data](root=args.data_dir, part='train', size=(args.height, args.width),
AttributeError: 'Namespace' object has no attribute 'data_dir'

**Comment by HEHE-code** [comment]
Have you resolved this issue?
